DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS PROTOCOL_1;
DROP TABLE IF EXISTS PROTOCOL_2;
DROP TABLE IF EXISTS PROTOCOL_3;
DROP TABLE IF EXISTS PROTOCOL_INSTANCE_1;
DROP TABLE IF EXISTS PROTOCOL_INSTANCE_2;
DROP TABLE IF EXISTS PROTOCOL_INSTANCE_3;

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

CREATE TABLE `USER` (
  `UID` varchar(100) NOT NULL,
  `USER_NAME` varchar(100) NOT NULL,
  `PASSWORD` varchar(100) NOT NULL,
  `P1ID` varchar(100),
  `P2ID` varchar(100),
  `P3ID` varchar(100)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO `USER` (`UID`, `USER_NAME`, `PASSWORD`) VALUES
('5552bc8b365d3', 'fanshi', '00cb3eed45ae0f2def4891d8f1fda16a');

CREATE TABLE `PROTOCOL_1` (
	`P1ID` varchar(100) NOT NULL,
	`UID` varchar(100) NOT NULL,
	`TRUVADA_1` varchar(100) NOT NULL,
	`REYATAZ_1` varchar(100) NOT NULL,
	`NORVIR_1` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `PROTOCOL_2` (
	`P2ID` varchar(100) NOT NULL,
	`UID` varchar(100) NOT NULL,
	`FUZEON_1` varchar(100) NOT NULL,
	`FUZEON_2` varchar(100) NOT NULL,
	`KALETRA_1` varchar(100) NOT NULL,
	`KALETRA_2` varchar(100) NOT NULL,
	`COMBIVIR_1` varchar(100) NOT NULL,
	`COMBIVIR_2` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `PROTOCOL_3` (
	`P3ID` varchar(100) NOT NULL,
	`UID` varchar(100) NOT NULL,
	`ATRIPLA_1` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `PROTOCOL_INSTANCE_1` (
	`P1ID` varchar(100) NOT NULL,
	`DAY` int(11),
	`DATE` DATE,
	`TRUVADA_1` varchar(100),
	`REYATAZ_1` varchar(100),
	`NORVIR_1` varchar(100)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `PROTOCOL_INSTANCE_2` (
	`P2ID` varchar(100) NOT NULL,
	`DAY` int(11),
	`DATE` DATE,
	`FUZEON_1` varchar(100),
	`FUZEON_2` varchar(100),
	`KALETRA_1` varchar(100),
	`KALETRA_2` varchar(100),
	`COMBIVIR_1` varchar(100),
	`COMBIVIR_2` varchar(100)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `PROTOCOL_INSTANCE_3` (
	`P3ID` varchar(100) NOT NULL,
	`DAY` int(11),
	`DATE` DATE,
	`ATRIPLA_1` varchar(100)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

ALTER TABLE `USER`
ADD PRIMARY KEY (`UID`);

ALTER TABLE `PROTOCOL_1`
ADD PRIMARY KEY (`P1ID`);

ALTER TABLE `PROTOCOL_2`
ADD PRIMARY KEY (`P2ID`);

ALTER TABLE `PROTOCOL_3`
ADD PRIMARY KEY (`P3ID`);